WebAppForArtists/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppForArtists.Models;

namespace WebAppForArtists.Controllers
{
    public class DashBoardController : Controller
    {
        public ActionResult UserDashBoard()
        {
            if (Session["UserID"] != null)
            {
                UserStorage us = new UserStorage();
                us.UserID = Int32.Parse(Session["UserID"].ToString());
                us.TagsId = new List<int>();
                us.Pictures = new List<string>();
                us.Tags = new List<Tag>();
                us.TagsNames = new List<string>();
                //us.CurrentTagID = "0";
                us.getTagsAndPicturesFromDB(us);

                ViewBag.tags = us.getTagsNames(us);
                ViewBag.pictures = us.Pictures;
                ViewBag.countedTags = us.Tags.Count;
                ViewBag.countedPictures = us.Pictures.Count;

                return View();
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }
    }
}

WebAppForArtists/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppForArtists.Models;

namespace WebAppForArtists.Controllers
{
    public class PictureController : Controller
    {
        // GET: Picture
        //[HttpPost] od tego był błąd
        [HttpGet]
        public ActionResult Upload()
        {
            UserStorage us = new UserStorage();
            us.UserID = Int32.Parse(Session["UserID"].ToString());
            us.TagsId = new List<int>();
            us.Pictures = new List<string>();
            us.Tags = new List<Tag>();
            us.TagsNames = new List<string>();
            //us.CurrentTagID = "0";
            us.getTagsAndPicturesFromDB(us);

            ViewBag.tags = us.TagsId;

            return View();
        }

        [HttpPost]
        public ActionResult Upload(Picture pictureModel)
        {
            string fileName = Path.GetFileNameWithoutExtension(pictureModel.PictureFile.FileName);
            string extension = Path.GetExtension(pictureModel.PictureFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            pictureModel.Name = "~/Content/Pictures/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Content/Pictures/"), fileName);
            pictureModel.PictureFile.SaveAs(fileName);
            pictureModel.UserID = Int32.Parse(Session["UserID"].ToString());

            UserStorage us = new UserStorage();
            us.UserID = Int32.Parse(Session["UserID"].ToString());
            us.TagsId = new List<int>();
            us.Pictures = new List<string>();
            us.Tags = new List<Tag>();
            us.TagsNames = new List<string>();
            //us.CurrentTagID = "0";
            us.getTagsAndPicturesFromDB(us);

            ViewBag.tags = us.TagsId/*getTagsNames(us)*/;

            using (DB_Model_Entities db = new DB_Model_Entities())
            {
                db.Pictures.Add(pictureModel);
                db.SaveChanges();
                return RedirectToAction("ShowPicture", new { id = pictureModel.PictureID });
            }
            ModelState.Clear();
            return View();
        }

        //public ActionResult ShowPicture()
        //{
        //    Picture pictureModel = new Picture();
        //    using (DB_Model_Entities db = new DB_Model_Entities())
        //    {
        //        pictureModel = db.Pictures.Where(x => x.PictureID == 2).FirstOrDefault();
        //    }
        //    return View(pictureModel);
        //}

        [HttpGet]
        public ActionResult ShowPicture(int id)
        {
            Picture pictureModel = new Picture();
            using (DB_Model_Entities db = new DB_Model_Entities())
            {
                pictureModel = db.Pictures.Where(x => x.PictureID == id).FirstOrDefault();
            }
            return View(pictureModel);
        }

    }
}

WebAppForArtists/Views/DashBoard/UserDashBoard.cshtml
@model WebAppForArtists.Models.UserStorage

@{
    ViewBag.Title = "UserDashBoard";
}

<head>
    <link rel="Stylesheet" href="~/Content/ArtSpaceStyle.css">
</head>

<body background="~/Content/PageItems/sky2.jpg">
    <div class="containerMainPage">
        <div class="containerProfile">
            <div>
                @if (Session["FirstName"] != null)
                {
                    <p>Welcome @Session["FirstName"].ToString()! </p>
                }
            </div>
            <div>
                <img class="addPicBtn" style="width:80%;" src="~/Content/PageItems/AddPicBtn.png" onclick="location.href='@Url.Action("Upload", "Picture")'" />
                <img id="settingsBtn" style="width:40%;" src="~/Content/PageItems/settingsBtn.gif" onclick="location.href='@Url.Action("Settings", "Settings")'" />
            </div>
            <div>
                <h4>You have: </h4>
                <p>@ViewBag.countedPictures pictures</p>
                <p>@ViewBag.countedTags tags</p>
            </div>
        </div>
        <div class="containerPictures">
            @using (Html.BeginForm("UserDashBoard", "DashBoard", FormMethod.Post))
            {
                <div id="tagDropDown">@Html.DropDownListFor(model => model.CurrentTagID, new SelectList(ViewBag.tags), "Choose tag")</div>
            }

            <div class="pictureBoard">
                @foreach(var picturePath in ViewBag.pictures)
                {
                    <img src="@Url.Content(picturePath)"/>
                }
            </div>
        </div>
        <div class="containerNotes">
            <div class="note1">
                <h4>My notes:</h4>
                <textarea placeholder="Write here your inspirations, ideas and more..."></textarea>
            </div>
            <div class="note2">
                <h4>To paint next:</h4>
                <textarea> • &#13;&#10; • &#13;&#10; • &#13;&#10; • &#13;&#10; • &#13;&#10; • &#13;&#10; • </textarea>
            </div>
        </div>
    </div>
</body>